# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'

  assets:
    # Cambia este texto cada vez que quieras forzar a todos los usuarios a recargar
    version: 'v_sf6_migracion_1'
    # Esto añade ?v_sf6_migracion_1 al final de todos los archivos css/js/img
    version_format: '%%s?%%s'

  #csrf_protection: true
  annotations: false
  http_method_override: false
  handle_all_throwables: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    #handler_id: null # COMENTAR ESTA LÍNEA
    handler_id: session.handler.native_file # Usar almacenamiento en archivos
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%' # Guardar sesiones en var/sessions
    cookie_secure: auto
    cookie_samesite: lax
    cookie_lifetime: 604800 # 7 días (en segundos)
    gc_maxlifetime: 604800  # 7 días (en segundos) - Tiempo en el servidor

  #esi: true
  #fragments: true
  php_errors:
    log: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file